nsa_homepage:
    path:     /
    defaults: { _controller: NSABundle:Default:prva }

nsa_test:
    path:    /testing_Bootstrap
    defaults: { _controller: NSABundle:Default:testing }

nsa_pokazi_nalogo:
    path:    /naloge/{id}
    defaults: { _controller: NSABundle:Default:pokaziNalogo }

nsa_vse_naloge:
    path:    /naloge
    defaults: { _controller: NSABundle:Default:vseNaloge }

nsa_success:
    path:    /success
    defaults: { _controller: NSABundle:Default:success }

nsa_dodaj_nalogo:
    path:    /dodaj_nalogo
    defaults: { _controller: NSABundle:Default:dodajNalogo }

nsa_pokazi_profesorja:
    path:    /prof/{id}
    defaults: { _controller: NSABundle:Default:pokaziProfesorja }

nsa_vsi_profesorji:
    path:    /prof
    defaults: { _controller: NSABundle:Default:vsiProfesorji }

nsa_dodaj_profesorja:
    path:    /dodaj_profesorja
    defaults: { _controller: NSABundle:Default:dodajProfesorja }

nsa_pokazi_rezervacijo:
    path:    /rezervacije/{id}
    defaults: { _controller: NSABundle:Default:pokaziRezervacijo }

nsa_vse_rezervacije:
    path:    /rezervacije
    defaults: { _controller: NSABundle:Default:vseRezervacije }

nsa_dodaj_rezervacijo:
    path:    /dodaj_rezervacijo
    defaults: { _controller: NSABundle:Default:dodajrezervacijo }

nsa_pokazi_prosnjo:
    path:    /prosnje/{id}
    defaults: { _controller: NSABundle:Default:pokaziProsnjo }

nsa_vse_prosnje:
    path:    /prosnje
    defaults: { _controller: NSABundle:Default:vseProsnje }

nsa_dodaj_prosnjo:
    path:    /dodaj_prosnjo
    defaults: { _controller: NSABundle:Default:dodajProsnjo }