nsa_homepage:
    path:     /
    defaults: { _controller: NSABundle:Default:prva }

nsa_test:
    path:    /testing_Bootstrap
    defaults: { _controller: NSABundle:Default:testing }

nsa_pokazi_nalogo:
    path:    /naloge/{id}
    defaults: { _controller: NSABundle:Default:pokaziNalogo }

nsa_vse_naloge:
    path:    /naloge
    defaults: { _controller: NSABundle:Default:vseNaloge }

nsa_success:
    path:    /success
    defaults: { _controller: NSABundle:Default:success }

nsa_dodaj_nalogo:
    path:    /dodaj_nalogo
    defaults: { _controller: NSABundle:Default:dodajNalogo }

nsa_pokazi_profesorja:
    path:    /prof/{id}
    defaults: { _controller: NSABundle:Default:pokaziProfesorja }

nsa_vsi_profesorji:
    path:    /prof
    defaults: { _controller: NSABundle:Default:vsiProfesorji }

