nsa_homepage:
    path:     /hello/{name}
    defaults: { _controller: NSABundle:Default:index }

nsa_test:
    path:    /testing_Bootstrap
    defaults: { _controller: NSABundle:Default:testing }

nsa_pokazi_nalogo:
    path:    /naloge/{id}
    defaults: { _controller: NSABundle:Default:pokaziNalogo }

nsa_vse_naloge:
    path:    /naloge
    defaults: { _controller: NSABundle:Default:vseNaloge }

nsa_pokazi_profesorja:
    path:    /prof/{id}
    defaults: { _controller: NSABundle:Default:pokaziProfesorja }

nsa_vsi_profesorji:
    path:    /prof
    defaults: { _controller: NSABundle:Default:vsiProfesorji }