security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        example:
            entity: {class NSA\Bundle\Entity\User, property: username}


    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path:  /login
                use_forward:  false
                check_path:  /login_check
                always_use_default_target_path:  true
                default_target_path: /testing_Bootstrap
                #success_handler: jan_projekt.component.authentication.handler.login_success_handler
                use_referer: true
            logout:
                path: /logout
                target: /
#                always_use_default_target_path:  true
#                default_target_path: /prva
                #success_handler: jan_projekt.component.authentication.handler.logout_success_handler
            anonymous:    true

   # access_control:
    #    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
     #   - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
      #  - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
       # - { path: ^/admin/, role: ROLE_ADMIN }
        #- { path: ^/delovno_mesto/dodaj_delovno_mesto, role: ROLE_USER }
        #- { path: ^/seznam_prijav, role: ROLE_USER }
        #- { path: ^/prijava/id, role: ROLE_USER }
        #- { path: ^/prijava, role: ROLE_USER }
        #- { path: ^/delovnomesto, role: ROLE_ADMIN }
        #- { path: ^/zaposlovalec, role: ROLE_ADMIN }
        #- { path: ^/prijave, role: ROLE_ADMIN }